export const SET_UPLOADED_FILE = 'SET_UPLOADED_FILE';
export const SET_UPLOADED_FILE_STRUCTURE_DESCRIPTION = 'SET_UPLOADED_FILE_STRUCTURE_DESCRIPTION';
export const CLEAR_UPLOAD_STATE = 'CLEAR_UPLOAD_STATE';
